# SITE CONFIGURATION
baseurl: "/t6tos"
url: ""

# THEME-SPECIFIC CONFIGURATION
title: Economic Research Centre, HKIAPS, CUHK                               # site's title

description: "ERC, HKIAPS, CUHK"      # used by search engines
avatar: assets/img/CUHK_logo.jpg                         # Empty for no avatar in navbar
favicon: assets/img/CUHK_logo.jpg                             # Icon displayed in the tab

# Header and footer text
header_text: Economic Research Centre # Change Blog header text
header_feature_image: assets/img/index_hero2.jpg
footer_text: >
  Copyright 2020 ERC, HKIAPS.

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
